language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install -r dev-requirements.txt
{%- if cookiecutter.package_requirements != "Type any packages required, leaving spaces in between each name. Press enter if none." %}
  - pip install -r requirements.txt
{%- endif %}

script:
  - python -m pytest --cov=. tests/

after_success:
  - coverage report
  - coveralls

jobs:
  include:
  - stage: deploy
    if: branch = master AND (NOT type IN (pull_request))
    before_install:
    - nvm install lts/* --latest-npm
    python:
    - "3.6"
    install:
    - pip install -r dev-requirements.txt
{%- if cookiecutter.package_requirements != "Type any packages required, leaving spaces in between each name. Press enter if none." %}
    - pip install -r requirements.txt
{%- endif %}
    - npm install @semantic-release/exec
    script:
    - git config --global user.email "releases@ladybug.tools"
    - git config --global user.name "ladybugbot"
    - npx semantic-release
  - stage: docs
    if: branch = master AND (NOT type IN (pull_request))
    script:
    - sphinx-apidoc -f -e -d 4 -o ./docs ./{{cookiecutter.pkg_name}}
    - sphinx-build -b html ./docs ./docs/_build/docs
    deploy:
      provider: pages
      skip_cleanup: true
      github-token: $GH_TOKEN
      keep-history: false
      local_dir: docs/_build/
      on:
        branch: master
